name: "CLA"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: "CLA Assistant"
        if: >
          (github.event_name == 'issue_comment' && contains(github.event.comment.body || '', 'recheck')) ||
          (github.event_name == 'issue_comment' && contains(github.event.comment.body || '', 'I have read the CLA Document and I hereby sign the CLA')) ||
          github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          PERSONAL_ACCESS_TOKEN: ${{ steps.create_token.outputs.token }}
        with:
          path-to-signatures: 'signatures-v3.json'
          path-to-document: 'https://github.com/open-domains/register/blob/main/terms.md'
          branch: 'main'
          allowlist: od-bot,bot*,kyro3400
          remote-organization-name: 'open-domains'
          remote-repository-name: 'cla'
          lock-pullrequest-aftermerge: false

      - name: Add CLA Signed
        uses: actions-ecosystem/action-add-labels@v1
        if: >
          (github.event_name == 'issue_comment' && contains(github.event.comment.body || '', 'recheck')) ||
          (github.event_name == 'issue_comment' && contains(github.event.comment.body || '', 'I have read the CLA Document and I hereby sign the CLA')) ||
          github.event_name == 'pull_request_target'
        with:
          labels: "CLA Signed"
          github_token: ${{ steps.create_token.outputs.token }}

      - name: Remove CLA Required
        uses: actions-ecosystem/action-remove-labels@v1
        if: >
          (github.event_name == 'issue_comment' && contains(github.event.comment.body || '', 'recheck')) ||
          (github.event_name == 'issue_comment' && contains(github.event.comment.body || '', 'I have read the CLA Document and I hereby sign the CLA')) ||
          github.event_name == 'pull_request_target'
        with:
          labels: "CLA Required"
          github_token: ${{ steps.create_token.outputs.token }}

      - name: Add CLA Required on Failure
        if: ${{ failure() }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "CLA Required"
          github_token: ${{ steps.create_token.outputs.token }}
