name: Validation

on:
    pull_request:

    push:
        branches: [main]
        paths:
            - "domains/*"
            - "tests/*"
            - "utils/*"
            - ".github/workflows/validate.yml"
            - "dnsconfig.js"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-validation
    cancel-in-progress: true

jobs:
    dns:
        name: DNS
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - id: create_token
              uses: tibdex/github-app-token@v2
              with:
               app_id: ${{ secrets.APP_ID }}
               private_key: ${{ secrets.PRIVATE_KEY }}

            - name: Check DNS
              id: dns_check
              uses: is-a-dev/dnscontrol-action@main
              with:
               args: check
               config_file: "dnsconfig.js"

            - name: Add Validated DNS Label
              if: ${{ steps.dns_check.outcome == 'success' }}
              uses: actions-ecosystem/action-add-labels@v1
              with:
               labels: "Validated DNS"
               github_token: ${{ steps.create_token.outputs.token }}
            - name: Remove Invalid DNS Label
              if: ${{ steps.dns_check.outcome == 'success' }}
              uses: actions-ecosystem/action-remove-labels@v1
              with:
               labels: "Invalid DNS"
               github_token: ${{ steps.create_token.outputs.token }}

            - name: Add Invalid DNS Label
              if: ${{ failure() }}
              uses: actions-ecosystem/action-add-labels@v1
              with:
               labels: "Invalid DNS"
               github_token: ${{ steps.create_token.outputs.token }}
            - name: Remove Validated DNS Label
              if: ${{ failure() }}
              uses: actions-ecosystem/action-remove-labels@v1
              with:
               labels: "Validated DNS"
               github_token: ${{ steps.create_token.outputs.token }}


    tests:
        name: Tests
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: npm install

            - run: npm test
