name: Validation

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  check:
    name: DNSControl Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gacts/install-dnscontrol@v1
        with: 
          version: 3.31.4



      - run: dnscontrol check
